### ISSUE TITLE
Version numbers in latest MOODLE_32_STABLE branch will cause downgrade errors

### ISSUE THREAD

**Issue by logan-reynolds** [kaltura/moodle_plugin#150]
The version numbers in all components in the latest commit 6ad2703 on MOODLE_32_STABLE branch are at 2017062132, which would cause downgrade errors across all Kaltura components when users upgrade from the 31 branch - this is because the version number on all components in the MOODLE_31_STABLE branch are already at 2017062531.  We've encountered this before and just clarified that the version number in a given branch much always be higher than the highest version number in the preceding branch.

**Comment by muli** [comment]
You're right.
We will fix this ASAP.

Sorry about that.

**Comment by muli** [comment]
@gonenradai, I updated the `version.php` files in MOODLE_32_DEV to be 2017062532.
Please let me know if it's OK and I will merge it to the STABLE branch.

**Comment by gonenradai** [comment]
go ahead.
merge and I'l update the package in moodle.org

**Comment by muli** [comment]
Done.

**Comment by gonenradai** [comment]
new package uploaded to moodle.org
