### ISSUE TITLE
Embed Kaltura Videos not working with long course title!

### ISSUE THREAD

**Issue by joelsrf** [kaltura/moodle_plugin#154]
Hello 

We're experiencing an issue with Moodle 3.2 and the lastest commit of the [MOODLE_32_STABLE](https://github.com/kaltura/moodle_plugin/commit/eeffba24ed3f62dbdb69d186d2e3e9dfa90fef57) branch. If the fullname of a course is long as for example _VorbereitungProg, Vorbereitungskurs Programmieren (Java), Semester Information /AS 18, Max Muster and Hans Muster_ all embedded kaltura videos are not working anymore and the following error gets displayed:

> A required parameter (url) was missing 
![screen shot 2017-07-21 at 14 01 34](https://user-images.githubusercontent.com/20297204/28462799-34131fa2-6e1d-11e7-8385-2d77df93a758.png)

When shortening the fullname of the course, the videos are working again!

However, when testing with a very long fullname such as: 

> abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq stuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst

It is working until I add a space somewhere in the line!

When downloading and comparing the "Kaltura package libraries" logs of a working video being called (short course fullname) and a non-working video (with a long course fullname) the only difference beside the _context_title_ and _resource_link_title_ is a quite shorter _custom_publishdata_.

This is a very serious and important issue for us! A prompt fix is needed!

Thanks in advance for your help!

**Comment by muli** [comment]
@joelschmid91 - thank you very much for the report!
I will look into it.

**Comment by joelsrf** [comment]
It seems like the _global $PAGE_ variable in _/local/kaltura/service.php_ is empty. However, we don't have any problems with other plugins concerning the length of the course fullname.

Thanks!

**Comment by muli** [comment]
@joelschmid91,

This issue is caused by a change introduced by Moodle 3.2 (LTI library), that essentially strips a long name - which breaks the validation on KAF side. See here: 
https://tracker.moodle.org/browse/MDL-58770.

Luckily, a regression bug was opened a few days ago, and there's already a fix: https://tracker.moodle.org/browse/MDL-59490.
