### ISSUE TITLE
line 97 of /local/kalturamediagallery/lib.php can trigger "Call to a member function add() on boolean"

### ISSUE THREAD

**Issue by lucaboesch** [kaltura/moodle_plugin#157]
Please inquire this. Taken off the MOODLE_32_DEV branch.

Error: Call to a member function add() on boolean
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 97 of /local/kalturamediagallery/lib.php: Error thrown
    line 1405 of /lib/navigationlib.php: call to local_kalturamediagallery_extend_navigation()
    line 224 of /blocks/navigation/block_navigation.php: call to global_navigation->initialise()
    line 166 of /blocks/navigation/block_navigation.php: call to block_navigation->get_navigation()
    line 288 of /blocks/moodleblock.class.php: call to block_navigation->get_content()
    line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 1179 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1231 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 538 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
    line 39 of /theme/bootstrapbase/renderers/core_renderer.php: call to core_renderer->standard_head_html()
    line 61 of /theme/bfh/layout/frontpage.php: call to theme_bootstrapbase_core_renderer->standard_head_html()
    line 1110 of /lib/outputrenderers.php: call to include()
    line 1040 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 114 of /index.php: call to core_renderer->header()

**Comment by muli** [comment]
Hi @lucaboesch, thank you for this report.

A fix will be released soon.

**Comment by muli** [comment]
Issue is now fixed, with the new released version for 3.2 and 3.3.
