### ISSUE TITLE
Allow kaltura_vidassign submitted videos to be downloaded.

### ISSUE THREAD

**Issue by lucaboesch** [kaltura/moodle_plugin#163]
If I'm not wrong, there's no possibility to bulk download or download submitted videos through kaltura_vidassign in Moodle.
Please note this as feature request.
(And please do correct me if I was wrong).

**Comment by idodido** [comment]
Hi @lucaboesch 
no download is currently available. We will look into the option of adding it. 

If possible, I would recommend sending an email to Kaltura Customer Care with this feature request and others - this way the Kaltura team can make sure it does not get forgotten or lost.
