### ISSUE TITLE
Intermittent failure to rewrite URL when importing kaltura video resources

### ISSUE THREAD

**Issue by mackensen** [kaltura/moodle_plugin#164]
We've had occasional problems when importing kaltura video resources from one course to another. In this situation, the `KALTURA_URI_TOKEN` is doubled instead of replaced. As a result, we get an entry like this in the `mdl_kalvidres` table:

```
| 2180 | 1_ptp7uelk |   6709411 | http://kaltura-kaf-uri.comkaltura-kaf-uri.com/browseandembed/index/media/entryid/1_ptp7uelk/showDescription/true/showTit |
```

On the public facing side the first of these tokens is translated, so Moodle tries (and fails) to reach yourmoodlekaf.kaf.kaltura.comkaltura-kaf-uri.com.

The instructor can resolve the issue by replacing the media. We don't have more than a dozen of these failures out of 2000+ resources, but it's puzzling for the instructor.

**Comment by muli** [comment]
Hello @mackensen,
Thank you for submitting this issue.

Can you please elaborate regarding the import process you mentioned? Did you run the migration script bundled in our plugin package? Some other external script?

Please share as much information as possible.

Thank you.

**Comment by mackensen** [comment]
Hi @muli, nothing so complicated as that, just importing materials from one course to another using the standard Moodle import process.

**Comment by muli** [comment]
Unfortunately, unless we have more information regarding the issue and without reproducible steps, I don't think we should spend time investigating this.
