### ISSUE TITLE
Comments does not update via Single view grading

### ISSUE THREAD

**Issue by cdipe** [kaltura/moodle_plugin#167]
Using Moodle 3.2.7 with Kaltura release 4.1 (2017062532)

When a teacher writes a comment on an assignment on the quick grade page /mod/kalvidassign/grade_submissions.php, with OR without setting a grade, and selects Save feedback, the comment becomes visible to the student. 

But, when a teacher selects Grade for assignment and writes a comment on an assignment on the single view page mod/kalvidassign/single_submission.php, without setting a grade, and selects Save changes, the comment does NOT become visible to the student. 
When using the single view page for grading, the teacher must always set or change the grade, for the new comments to become visible to the student.
The teacher always see all her own comments though, even when the student do not see them, and this becomes very confusing.

**Comment by muli** [comment]
Fixed in v4.1.4 for Moodle 3.4, 3.5 and 3.6.
