### ISSUE TITLE
Video Assignment spams users

### ISSUE THREAD

**Issue by amandadoughty** [kaltura/moodle_plugin#173]
Version 2017120634

In mod/kalviassign/locallib.php #251

Function kalvidassign_get_graders gets potential graders with this function call:
$potgraders = get_users_by_capability($context, 'mod/kalvidassign:gradesubmission', '', '', '', '', '', '', false, false);

However this results in emails being sent to all of our category level role assignments. To follow the policy in core moodle, only users enrolled on the course should get emails and the call should be:
$potgraders = get_enrolled_users($context, "mod/kalvidassign:gradesubmission", null, 'u.*', null, null, null, true);

**Comment by muli** [comment]
@idodido, can you please add this bug to our next version planning?

**Comment by idodido** [comment]
opened KMS-18572.

**Comment by muli** [comment]
Fixed in v4.1.4 for Moodle 3.4, 3.5 and 3.6.
