### ISSUE TITLE
For 3.6, remove reference to lib/eventslib.php and its deprecated functions

### ISSUE THREAD

**Issue by lucaboesch** [kaltura/moodle_plugin#185]
See: lib/upgrade.txt
* The eventslib.php file has been deleted and its functions have been moved to deprecatedlib.php. The affected functions are:
  - events_get_cached()
  - events_uninstall()
  - events_cleanup()
  - events_dequeue()
  - events_get_handlers()

**Comment by muli** [comment]
Hi @lucaboesch, in this commit: https://github.com/kaltura/moodle_plugin/commit/1090b41c6fa359bfda6ac49199438b86eaa3b105 we removed the include to the deleted file.

Are you still encountering an issue with the installation of our plugin?

**Comment by muli** [comment]
Closing due to lack of response.
