### ISSUE TITLE
Sync MOODLE_35_STABLE branch

### ISSUE THREAD

**Issue by adpe** [kaltura/moodle_plugin#189]
Hello @alon1980 @muli 

When do you update the `MOODLE_35_STABLE` branch? In the meantime there were two updates in the `MOODLE_35_DEV` branch but the stable still is on an old state.

Thanks for more information about it
Adrian

**Comment by gonenradai** [comment]
Adrian,

we update the STABLE branch after dev changes pass QA and are cleared for release.
@idodido (product manager) can provide expected timeline for the recent changes.

**Comment by muli** [comment]
I believe that this issue can be closed since we handled it already.

Thanks @adpe.
