### ISSUE TITLE
Release of MOODLE_36_STABLE

### ISSUE THREAD

**Issue by adpe** [kaltura/moodle_plugin#190]
Hello @alon1980 @muli 

When do you plan to release the plugin for Moodle Version 3.6+?

Greets
Adrian

**Comment by gonenradai** [comment]
we already have a plugin for moodle 3.6 - https://moodle.org/plugins/pluginversions.php?id=447

**Comment by adpe** [comment]
HI @gonenradai 

Thanks I see. So, here on GitHub is missing the `MOODLE_36_STABLE` branch, the `*_DEV` is there.

**Comment by gonenradai** [comment]
that's a mistake, but since we've added content to the 36_DEV branch already, we will create a 36_STABLE once this content is approved by our QA.

**Comment by adpe** [comment]
Okay great. Thank you.
