### ISSUE TITLE
Kaltura embedded video script cross-origin request blocked

### ISSUE THREAD

**Issue by logan-reynolds** [kaltura/moodle_plugin#191]
When embedding a Kaltura video via the atto editor in a course that utilizes pop-up modals for section content (i.e. format_grid), we're finding that the following (sanitized) error is encountered in browser console which prevents the video player and content from loading:

``
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://stats.kaltura.com/api_v3/index.php?service=stats&apiVersion=3.1&expiry=86400&clientTag=kwidget%3Av2.74.1&format=1&ignoreNull=1&action=collect&event:eventType=1&event:clientVer=2.74.1&event:currentPoint=0&event:duration=181&event:eventTimestamp=1551291107733&event:isFirstInSession=false&event:objectType=KalturaStatsEvent&event:partnerId=######&event:sessionId=#####-#####-#####-####-#####&event:uiconfId=######&event:seek=false&event:entryId=0_khwgbsqr&event:historyEvents=###############-2-2&event:widgetId=_1747731&event:referrer=############. (Reason: CORS request did not succeed).
``

The same video loads with no problem when switching to a non-modal course format, with video loading and playing correctly in a single stand-alone page.  This leads me to think that there is some problem caused by embedding the script which fetches/loads the Kaltura video player inside an iframe, and this problem is not triggered when on a standard page because it does not violate the Same Origin Policy.

**Comment by gonenradai** [comment]
Hi @logan-reynolds 
The specific request you're specifying here is analytics only and should not block playback.
Please open a support ticket via Kaltura customer care so we can further investigate the issue, which might require details that should not be posted here.

**Comment by ghost** [comment]
Hey @logan-reynolds can you share your solution or what was causing the CORS error ? Sitting on the same Problem.
