### ISSUE TITLE
Embedded files in textual intro for kalvidres not saved in backup

### ISSUE THREAD

**Issue by rabser** [kaltura/moodle_plugin#193]
If you try to embed a file into the intro of a kaltura video resource, simply by uploading and linking it into the introduction text, when you do a backup of the moodle course, these files are not saved into the backup.

To solve this bug, i added these lines:
 ```
 // Define file annotations
        $kalvidres->annotate_files('mod_kalvidres', 'intro', null); // This file areas haven't itemid
```
just before the return for function define_structure 
into backup/moodle2/backup_kalvidres_stepslib.php

Hope this helps

**Comment by muli** [comment]
Thanks @rabser, we will take a look into this.

**Comment by muli** [comment]
Fixed in https://github.com/kaltura/moodle_plugin/commit/1abb1433f6e29efcbef14f2c921977af6657d512.
