### ISSUE TITLE
Problem installing on M3.7

### ISSUE THREAD

**Issue by 2shediac** [kaltura/moodle_plugin#237]
When trying to install mod/kalvidassign on M3.7 get an error /lib/eventslib.php): failed to open stream: No such file or directory - 

version 2019080435

**Comment by muli** [comment]
Hi there @2shediac,

You are trying to install a plugin version that is compatible with Moodle 3.5. Please install 2019080437 which you can find here: https://github.com/kaltura/moodle_plugin/releases/tag/4.2.4-3.7 or from the Moodle official website: https://moodle.org/plugins/pluginversions.php?id=447.
