### ISSUE TITLE
Video → Add media button is double styled as button

### ISSUE THREAD

**Issue by lucaboesch** [kaltura/moodle_plugin#271]
Hi.
In our theme that's more obvious, but in the kalvidres resource plugin in the interface to choose a video the Video → Add media button is styled as button twice.
It seems as if it was a button inside a button. I hope this screen grab makes this clear.

<img width="603" alt="grafik" src="https://user-images.githubusercontent.com/377279/72220196-8d25b000-354e-11ea-97cf-1b822270bc61.png">

Best,

Luca

**Comment by adpe** [comment]
Hi @lucaboesch 

Check out https://github.com/kaltura/moodle_plugin/pull/245 as it should be already fixed.

HTH,
Adrian

**Comment by lucaboesch** [comment]
Yeah, but it is missing in the 3.6 release, Adrian.

**Comment by lucaboesch** [comment]
@muli it would be dope if you could add this to the MOODLE_36_DEV branch, too.
Thanks in advance!

**Comment by muli** [comment]
@noychn-kaltura, can you please take care of this? :)

**Comment by noychn-kaltura** [comment]
@muli sure

**Comment by adpe** [comment]
Push @noychn-kaltura 

Greets,
Adrian
