### ISSUE TITLE
Undefined index: submission on LTI launch

### ISSUE THREAD

**Issue by Kemmotar83** [kaltura/moodle_plugin#278]
Hi, I've just updated all plugins in the _Kaltura Video Package Kaltura Video Plugin v4.2.6 for Moodle v3.8_ in a Moodle v. 3.8.1 installation. Previous version of plugins was v4.2.5 for Moodle v3.7, that worked fine also in Moodle 3.8.

I've not enable the Clone submission setting.

Now, everytime that I open a Kaltura page (ie. My Media, Kaltura Video Resource, ...) the following message is displayed.

```
Notice: Undefined index: submission in /var/www/.../local/kaltura/locallib.php on line 393
Call Stack
#	Time	Memory	Function	Location
1	0.0002	404192	{main}( )	.../lti_launch.php:0
2	0.0201	3532984	local_kaltura_request_lti_launch( )	.../lti_launch.php:69
```

It's a _Notice_ and it will be displayed only with debugging enabled, so it's not critical. It seems only a missing check on a key in the _$ltirequest_ array.

Thanks,
Giorgio

**Comment by noychn-kaltura** [comment]
@Kemmotar83 thanks for opening this issue. I created a PR to solve it.
