### ISSUE TITLE
Fatal error in require a not eisting file "attoembed.php"

### ISSUE THREAD

**Issue by adpe** [kaltura/moodle_plugin#280]
Hi @muli @noychn-kaltura 

The embed function in `atto editor is broken` as you renamed the require once function but removed the file!

![image](https://user-images.githubusercontent.com/9467708/76199689-9f3f6a00-61f0-11ea-9fb3-b2941a817838.png)

The bug was introduced in commit https://github.com/kaltura/moodle_plugin/commit/bcd730f4238ed3238815800b86f443e5fe040e96 and should be fixed as soon as possible!

At the moment we've a workaround but I think a lot of users are affected.

Cheers,
Adrian

**Comment by noychn-kaltura** [comment]
@adpe Thanks for opening this issue, we will solve it asap.

**Comment by jtsafran** [comment]
@adpe what was your workaround?  I'm seeing this, as well.  Moodle 3.7.3  Kaltura 2020010537

**Comment by noychn-kaltura** [comment]
Hi @jtsafran,
A new version of our plugin was just released with a fix to this issue: version 4.2.7

**Comment by adpe** [comment]
Hi @jtsafran 

> @adpe what was your workaround? I'm seeing this, as well. Moodle 3.7.3 Kaltura 2020010537

It would be better if you can upgrade the Kaltura plugin, if not here is our workaround we're using:

We've just checked out the branch on an older state:
```bash
git fetch origin f055d146bb1e416af7cf339b469c91891416ed4b
git reset --hard FETCH_HEAD
```

And then in the Moodle database we set manually the plugin version to the older ones:
```sql
UPDATE mdl_config_plugins SET value = 2019111437 WHERE plugin LIKE '%kaltura%' AND name = 'version';
UPDATE mdl_config_plugins SET value = 2019111437 WHERE plugin LIKE '%mymedia%' AND name = 'version';
UPDATE mdl_config_plugins SET value = 2019111437 WHERE plugin LIKE '%kalvid%' AND name = 'version';
```

**Comment by adpe** [comment]
Push @noychn-kaltura

This issue can be closed.

Greets,
Adrian
