### ISSUE TITLE
Display description option

### ISSUE THREAD

**Issue by lucaboesch** [kaltura/moodle_plugin#292]
I was asked how it was possible to show a Kaltura video resource description on a course page.
In my opinion that option is missing.
<img width="1106" alt="kalvidresource_show_description" src="https://user-images.githubusercontent.com/377279/79830661-324df100-83a6-11ea-8e8e-a898ba0a8479.png">
Thanks,
Luca

**Comment by lisakbaker** [comment]
I have been asked the same question by our course officers. Now that video assignment is being used more extensively, course officers want to be able to add an assignment description directly onto the module page, as they can with other assignment types n Moodle.

**Comment by goggo24** [comment]
Same here - it would be great if you can include this in the next version. It's not a lot of work, but would have a great impact.

**Comment by idodido** [comment]
resovled in https://kaltura.atlassian.net/browse/KMS-20967 - version 4.3.0
