### ISSUE TITLE
Blank popup when adding kaltura media in Atto

### ISSUE THREAD

**Issue by cdipe** [kaltura/moodle_plugin#294]
We have recently upgraded to moodle 3.83 and the latest Kaltura package (2020010538), and have got a problem with the Atto editor. When selecting the Kaltura media button, the user's media is visible. But when selecting a media the popup goes blank. In the inspector/console we can see an error, "Failed to load resource: the server responded with a status of 500 (Internal Server Error)". 

In TinyMCE everything works as it should.

![console](https://user-images.githubusercontent.com/14754240/84771158-33cc1c00-afd9-11ea-9729-4b2c77f84b40.png)

**Comment by noychn-kaltura** [comment]
@cdipe 
It's a known issue in this version.
Please update your package to the latest version **Kaltura Video Plugin v4.2.7** (2020030938),
it fixes this specific issue.

**Comment by cdipe** [comment]
@noychn-kaltura Thank you (I thought we had the latest version!)
