### ISSUE TITLE
No video in iframe on safari

### ISSUE THREAD

**Issue by rschrenk** [kaltura/moodle_plugin#312]
On Safari in iOS (and some users also reported that the problem occurs on iOS in Firefox too) videos cannot  be embedded unless tracking protection is disabled due to third party cookies.

It would be great to find a solution for this, because most users are not able to or don't want to disable the tracking protection.

**Comment by rlorenzo** [comment]
@rschrenk You need to setup your KAF to be under the same domain as your Moodle server. See https://knowledge.kaltura.com/help/how-to-avoid-the-3rd-party-cookie-error-message-in-the-kaf-based-lms-integrations

**Comment by rschrenk** [comment]
thanks for that link.
