### ISSUE TITLE
Affero General Public License

### ISSUE THREAD

**Issue by ht2** [kaltura/moodle_plugin#341]
There are numerous references to Affero General Public Licensing in the following files.

https://github.com/kaltura/moodle_plugin/search?q=Affero+General+Public+License

Could you please clarify the status of theses files and if you deem them held under AGPL restrictions.

**Comment by gonenradai** [comment]
@ht2 
the files you are referring to are an external package which is the Kaltura API Client Library which comes with its own license and is used by the moodle plugin.
we cannot change the license of the client library.

the source of these files is https://github.com/kaltura/KalturaGeneratedAPIClientsPHP

**Comment by ht2** [comment]
Thanks @gonenradai - good to know. For anyone who comes across this down the line, reading up on AGPL further it seems that [Moodle allows](https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing) for cherry picking of files from one library into another, where it is [GPL compatible](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses), but the AGPL will only apply to the specific files included and does not copyleft into the rest of the GPL library.

> Notwithstanding any other provision of this License, you have permission to link or combine any covered work with a work licensed under version 3 of the GNU General Public License into a single combined work, and to convey the resulting work. The terms of this License will continue to apply to the part which is the covered work, but the work with which it is combined will remain governed by version 3 of the GNU General Public License

Ideally this lib would be linked to and referenced through dependency management (composer) or some attribution (the link you gave) given in a README on the plugin itself. Thanks for taking a look though and good we have it documented here now
